# Generated by Django 5.2.4 on 2025-07-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('MONTHLY', 'monthly'), ('ANNUAL', 'annual'), ('UNIQUE', 'unique'), ('BIWEEKLY', 'biweekly'), ('OTHER', 'Other')], max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIIs', 'Real Estate Fund'), ('CDB', 'CDB'), ('STOCK', 'Stock'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateField()),
                ('yield_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
